### ISSUE TITLE
Certbot is missing a Network Policy to allow the ACME challenge route to be accessed

### ISSUE THREAD

**Issue by WadeBarnes** [BCDevOps/certbot#25]
The certbot cron job generates a temporary route and service for the `*/.well-known/acme-challenge/` url.  However it does not create a corresponding Network Policy allowing ingress through that route to the pod.  In environments that do not define permissive ingress policies this results in the following error:
```
Requesting a certificate for email-verification-dev.vonx.io
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
Domain: <your-domain>
Type: unauthorized
Detail: 142.34.194.118: Invalid response from http://<your-domain>/.well-known/acme-challenge/Ae4zCggGtBv8Q3bvJqeFIP7B4PIe3I9PCieJSi-rJVk: 503
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 8080. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.
```

In addition to the temporary route and service, a temporary network policy should also be created to allow ingress to the certbot pod.  The service, route, and np should be created and cleaned up as a matching set, as is done now with the route and service.

As a workaround the following Network Policy can be added to the namespace in which the certbot jobs are running:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: certbot-allow-ingress
  labels:
    app: certbot
    name: certbot-allow-ingress
    role: certbot
spec:
  podSelector:
    matchLabels:
      app: certbot
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
```
